<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class Error 
{

    /**
     * @var string $error
     */
    private string $error;

    /**
     * @var string $code
     */
    private string $code;

    /**
     * @var array<string,mixed>|null $params
     */
    private ?array $params;

    /**
    * @return string
    */
    public function getError(): string
    {
        return $this->error;
    }

    /**
     * @param string $error Human-readable error message.
     */
    public function setError(string $error): self
    {
        $this->error = $error;

        return $this;
    }
    /**
    * @return string
    */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * @param string $code Machine-readable error code in SCREAMING_SNAKE_CASE.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }
    /**
    * @return array<string,mixed>|null
    */
    public function getParams(): ?array
    {
        return $this->params;
    }

    /**
     * @param array<string,mixed>|null $params Additional structured context for the error. May be omitted.
     */
    public function setParams(?array $params): self
    {
        $this->params = $params;

        return $this;
    }
}

