<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class Pagination 
{

    /**
     * @var int $page
     */
    private int $page;

    /**
     * @var int $perPage
     */
    private int $perPage;

    /**
     * @var int $total
     */
    private int $total;

    /**
     * @var int $totalPages
     */
    private int $totalPages;

    /**
    * @return int
    */
    public function getPage(): int
    {
        return $this->page;
    }

    /**
     * @param int $page Current page number (1-based).
     */
    public function setPage(int $page): self
    {
        $this->page = $page;

        return $this;
    }
    /**
    * @return int
    */
    public function getPerPage(): int
    {
        return $this->perPage;
    }

    /**
     * @param int $perPage Items per page.
     */
    public function setPerPage(int $perPage): self
    {
        $this->perPage = $perPage;

        return $this;
    }
    /**
    * @return int
    */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * @param int $total Total number of items across all pages.
     */
    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }
    /**
    * @return int
    */
    public function getTotalPages(): int
    {
        return $this->totalPages;
    }

    /**
     * @param int $totalPages Total number of pages.
     */
    public function setTotalPages(int $totalPages): self
    {
        $this->totalPages = $totalPages;

        return $this;
    }
}

