<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesFlagsRequest 
{

    /**
     * @var string[]|null $addFlags
     */
    private ?array $addFlags;

    /**
     * @var string[]|null $removeFlags
     */
    private ?array $removeFlags;

    /**
    * @return string[]|null
    */
    public function getAddFlags(): ?array
    {
        return $this->addFlags;
    }

    /**
     * @param string[]|null $addFlags addFlags
     */
    public function setAddFlags(?array $addFlags): self
    {
        $this->addFlags = $addFlags;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getRemoveFlags(): ?array
    {
        return $this->removeFlags;
    }

    /**
     * @param string[]|null $removeFlags removeFlags
     */
    public function setRemoveFlags(?array $removeFlags): self
    {
        $this->removeFlags = $removeFlags;

        return $this;
    }
}

