<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesSearchRequest 
{

    /**
     * @var \DateTime|null $since
     */
    private ?\DateTime $since;

    /**
     * @var \DateTime|null $before
     */
    private ?\DateTime $before;

    /**
     * @var string[]|null $flags
     */
    private ?array $flags;

    /**
     * @var string|null $uid
     */
    private ?string $uid;

    /**
     * @var string|null $subject
     */
    private ?string $subject;

    /**
     * @var string|null $from
     */
    private ?string $from;

    /**
     * @var string|null $to
     */
    private ?string $to;

    /**
     * @var string|null $cc
     */
    private ?string $cc;

    /**
     * @var string|null $body
     */
    private ?string $body;

    /**
     * @var string|null $header
     */
    private ?string $header;

    /**
     * @var int|null $larger
     */
    private ?int $larger;

    /**
     * @var int|null $smaller
     */
    private ?int $smaller;

    /**
     * @var string|null $text
     */
    private ?string $text;

    /**
    * @return \DateTime|null
    */
    public function getSince(): ?\DateTime
    {
        return $this->since;
    }

    /**
     * @param \DateTime|null $since since
     */
    public function setSince(?\DateTime $since): self
    {
        $this->since = $since;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getBefore(): ?\DateTime
    {
        return $this->before;
    }

    /**
     * @param \DateTime|null $before before
     */
    public function setBefore(?\DateTime $before): self
    {
        $this->before = $before;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getFlags(): ?array
    {
        return $this->flags;
    }

    /**
     * @param string[]|null $flags flags
     */
    public function setFlags(?array $flags): self
    {
        $this->flags = $flags;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getUid(): ?string
    {
        return $this->uid;
    }

    /**
     * @param string|null $uid uid
     */
    public function setUid(?string $uid): self
    {
        $this->uid = $uid;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSubject(): ?string
    {
        return $this->subject;
    }

    /**
     * @param string|null $subject subject
     */
    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getFrom(): ?string
    {
        return $this->from;
    }

    /**
     * @param string|null $from from
     */
    public function setFrom(?string $from): self
    {
        $this->from = $from;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getTo(): ?string
    {
        return $this->to;
    }

    /**
     * @param string|null $to to
     */
    public function setTo(?string $to): self
    {
        $this->to = $to;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getCc(): ?string
    {
        return $this->cc;
    }

    /**
     * @param string|null $cc cc
     */
    public function setCc(?string $cc): self
    {
        $this->cc = $cc;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getBody(): ?string
    {
        return $this->body;
    }

    /**
     * @param string|null $body body
     */
    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getHeader(): ?string
    {
        return $this->header;
    }

    /**
     * @param string|null $header header
     */
    public function setHeader(?string $header): self
    {
        $this->header = $header;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getLarger(): ?int
    {
        return $this->larger;
    }

    /**
     * @param int|null $larger larger
     */
    public function setLarger(?int $larger): self
    {
        $this->larger = $larger;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getSmaller(): ?int
    {
        return $this->smaller;
    }

    /**
     * @param int|null $smaller smaller
     */
    public function setSmaller(?int $smaller): self
    {
        $this->smaller = $smaller;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * @param string|null $text text
     */
    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }
}

