<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesDeleteBulkRequest 
{

    /**
     * @var int[] $uids
     */
    private array $uids;

    /**
    * @return int[]
    */
    public function getUids(): array
    {
        return $this->uids;
    }

    /**
     * @param int[] $uids Message UIDs to delete. 1-100 entries, each > 0.
     */
    public function setUids(array $uids): self
    {
        $this->uids = $uids;

        return $this;
    }
}

