<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesUpdateFlagsResultDataFailedInner 
{

    /**
     * @var int $uid
     */
    private int $uid;

    /**
     * @var string $reason
     */
    private string $reason;

    /**
    * @return int
    */
    public function getUid(): int
    {
        return $this->uid;
    }

    /**
     * @param int $uid uid
     */
    public function setUid(int $uid): self
    {
        $this->uid = $uid;

        return $this;
    }
    /**
    * @return string
    */
    public function getReason(): string
    {
        return $this->reason;
    }

    /**
     * @param string $reason reason
     */
    public function setReason(string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }
}

