<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FoldersFolder 
{

    /**
     * @var string $path
     */
    private string $path;

    /**
     * @var string $name
     */
    private string $name;

    /**
     * @var string $delimiter
     */
    private string $delimiter;

    /**
     * @var string $specialUse
     */
    private ?string $specialUse = null;

    /**
     * @var int $messageCount
     */
    private int $messageCount;

    /**
     * @var int $unreadCount
     */
    private int $unreadCount;

    /**
    * @return string
    */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * @param string $path Full hierarchical folder path including the delimiter.
     */
    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }
    /**
    * @return string
    */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name Leaf name of the folder.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string
    */
    public function getDelimiter(): string
    {
        return $this->delimiter;
    }

    /**
     * @param string $delimiter Hierarchy delimiter used by the IMAP server.
     */
    public function setDelimiter(string $delimiter): self
    {
        $this->delimiter = $delimiter;

        return $this;
    }
    /**
    * @return string
    */
    public function getSpecialUse(): ?string
    {
        return $this->specialUse;
    }

    /**
     * @param string $specialUse IMAP SPECIAL-USE attribute (RFC 6154). `null` for regular folders.
     */
    public function setSpecialUse(?string $specialUse): self
    {
        $this->specialUse = $specialUse;

        return $this;
    }
    /**
    * @return int
    */
    public function getMessageCount(): int
    {
        return $this->messageCount;
    }

    /**
     * @param int $messageCount Total number of messages in the folder.
     */
    public function setMessageCount(int $messageCount): self
    {
        $this->messageCount = $messageCount;

        return $this;
    }
    /**
    * @return int
    */
    public function getUnreadCount(): int
    {
        return $this->unreadCount;
    }

    /**
     * @param int $unreadCount Number of unread messages in the folder.
     */
    public function setUnreadCount(int $unreadCount): self
    {
        $this->unreadCount = $unreadCount;

        return $this;
    }
}

