<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesUpdateFlagsResultData 
{

    /**
     * @var int[] $successful
     */
    private array $successful;

    /**
     * @var \Hostinger\Model\V1FolderMessagesUpdateFlagsResultDataFailedInner[] $failed
     */
    private array $failed;

    /**
    * @return int[]
    */
    public function getSuccessful(): array
    {
        return $this->successful;
    }

    /**
     * @param int[] $successful successful
     */
    public function setSuccessful(array $successful): self
    {
        $this->successful = $successful;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesUpdateFlagsResultDataFailedInner[]
    */
    public function getFailed(): array
    {
        return $this->failed;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesUpdateFlagsResultDataFailedInner[] $failed failed
     */
    public function setFailed(array $failed): self
    {
        $this->failed = $failed;

        return $this;
    }
}

