<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesMessageAttachment 
{

    /**
     * @var string $id
     */
    private string $id;

    /**
     * @var string $contentType
     */
    private string $contentType;

    /**
     * @var int $sizeBytes
     */
    private int $sizeBytes;

    /**
     * @var bool $inline
     */
    private bool $inline;

    /**
     * @var string $filename
     */
    private ?string $filename = null;

    /**
     * @var string $contentId
     */
    private ?string $contentId = null;

    /**
    * @return string
    */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @param string $id Opaque attachment identifier. Use as the {attachmentId} path parameter on the download endpoint.
     */
    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return string
    */
    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @param string $contentType contentType
     */
    public function setContentType(string $contentType): self
    {
        $this->contentType = $contentType;

        return $this;
    }
    /**
    * @return int
    */
    public function getSizeBytes(): int
    {
        return $this->sizeBytes;
    }

    /**
     * @param int $sizeBytes sizeBytes
     */
    public function setSizeBytes(int $sizeBytes): self
    {
        $this->sizeBytes = $sizeBytes;

        return $this;
    }
    /**
    * @return bool
    */
    public function getInline(): bool
    {
        return $this->inline;
    }

    /**
     * @param bool $inline inline
     */
    public function setInline(bool $inline): self
    {
        $this->inline = $inline;

        return $this;
    }
    /**
    * @return string
    */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string $filename filename
     */
    public function setFilename(?string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }
    /**
    * @return string
    */
    public function getContentId(): ?string
    {
        return $this->contentId;
    }

    /**
     * @param string $contentId contentId
     */
    public function setContentId(?string $contentId): self
    {
        $this->contentId = $contentId;

        return $this;
    }
}

