<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesMoveBulkRequest 
{

    /**
     * @var int[] $uids
     */
    private array $uids;

    /**
     * @var string $targetFolder
     */
    private string $targetFolder;

    /**
    * @return int[]
    */
    public function getUids(): array
    {
        return $this->uids;
    }

    /**
     * @param int[] $uids Message UIDs to move. 1-100 entries, each > 0.
     */
    public function setUids(array $uids): self
    {
        $this->uids = $uids;

        return $this;
    }
    /**
    * @return string
    */
    public function getTargetFolder(): string
    {
        return $this->targetFolder;
    }

    /**
     * @param string $targetFolder Destination folder path.
     */
    public function setTargetFolder(string $targetFolder): self
    {
        $this->targetFolder = $targetFolder;

        return $this;
    }
}

