<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesMoveRequest 
{

    /**
     * @var string $targetFolder
     */
    private string $targetFolder;

    /**
    * @return string
    */
    public function getTargetFolder(): string
    {
        return $this->targetFolder;
    }

    /**
     * @param string $targetFolder Destination folder path.
     */
    public function setTargetFolder(string $targetFolder): self
    {
        $this->targetFolder = $targetFolder;

        return $this;
    }
}

