<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesMessage 
{

    /**
     * @var int $uid
     */
    private int $uid;

    /**
     * @var string $path
     */
    private string $path;

    /**
     * @var \DateTime $date
     */
    private \DateTime $date;

    /**
     * @var string[] $flags
     */
    private array $flags;

    /**
     * @var bool $unseen
     */
    private bool $unseen;

    /**
     * @var int $size
     */
    private int $size;

    /**
     * @var string $subject
     */
    private ?string $subject = null;

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessageAddress $from
     */
    private ?\Hostinger\Model\V1FolderMessagesMessageAddress $from = null;

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessageAddress[] $to
     */
    private array $to;

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessageAddress[] $cc
     */
    private array $cc;

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessageAddress[] $bcc
     */
    private array $bcc;

    /**
     * @var string $messageId
     */
    private ?string $messageId = null;

    /**
     * @var string $inReplyTo
     */
    private ?string $inReplyTo = null;

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessageAttachment[] $attachments
     */
    private array $attachments;

    /**
    * @return int
    */
    public function getUid(): int
    {
        return $this->uid;
    }

    /**
     * @param int $uid uid
     */
    public function setUid(int $uid): self
    {
        $this->uid = $uid;

        return $this;
    }
    /**
    * @return string
    */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * @param string $path path
     */
    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date date
     */
    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }
    /**
    * @return string[]
    */
    public function getFlags(): array
    {
        return $this->flags;
    }

    /**
     * @param string[] $flags flags
     */
    public function setFlags(array $flags): self
    {
        $this->flags = $flags;

        return $this;
    }
    /**
    * @return bool
    */
    public function getUnseen(): bool
    {
        return $this->unseen;
    }

    /**
     * @param bool $unseen unseen
     */
    public function setUnseen(bool $unseen): self
    {
        $this->unseen = $unseen;

        return $this;
    }
    /**
    * @return int
    */
    public function getSize(): int
    {
        return $this->size;
    }

    /**
     * @param int $size size
     */
    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }
    /**
    * @return string
    */
    public function getSubject(): ?string
    {
        return $this->subject;
    }

    /**
     * @param string $subject subject
     */
    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesMessageAddress
    */
    public function getFrom(): ?\Hostinger\Model\V1FolderMessagesMessageAddress
    {
        return $this->from;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessageAddress $from from
     */
    public function setFrom(?\Hostinger\Model\V1FolderMessagesMessageAddress $from): self
    {
        $this->from = $from;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesMessageAddress[]
    */
    public function getTo(): array
    {
        return $this->to;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessageAddress[] $to to
     */
    public function setTo(array $to): self
    {
        $this->to = $to;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesMessageAddress[]
    */
    public function getCc(): array
    {
        return $this->cc;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessageAddress[] $cc cc
     */
    public function setCc(array $cc): self
    {
        $this->cc = $cc;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesMessageAddress[]
    */
    public function getBcc(): array
    {
        return $this->bcc;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessageAddress[] $bcc bcc
     */
    public function setBcc(array $bcc): self
    {
        $this->bcc = $bcc;

        return $this;
    }
    /**
    * @return string
    */
    public function getMessageId(): ?string
    {
        return $this->messageId;
    }

    /**
     * @param string $messageId messageId
     */
    public function setMessageId(?string $messageId): self
    {
        $this->messageId = $messageId;

        return $this;
    }
    /**
    * @return string
    */
    public function getInReplyTo(): ?string
    {
        return $this->inReplyTo;
    }

    /**
     * @param string $inReplyTo inReplyTo
     */
    public function setInReplyTo(?string $inReplyTo): self
    {
        $this->inReplyTo = $inReplyTo;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1FolderMessagesMessageAttachment[]
    */
    public function getAttachments(): array
    {
        return $this->attachments;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessageAttachment[] $attachments attachments
     */
    public function setAttachments(array $attachments): self
    {
        $this->attachments = $attachments;

        return $this;
    }
}

