<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesMessageText 
{

    /**
     * @var string $text
     */
    private string $text;

    /**
     * @var string $html
     */
    private string $html;

    /**
    * @return string
    */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * @param string $text text
     */
    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }
    /**
    * @return string
    */
    public function getHtml(): string
    {
        return $this->html;
    }

    /**
     * @param string $html html
     */
    public function setHtml(string $html): self
    {
        $this->html = $html;

        return $this;
    }
}

