<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesCollection 
{

    /**
     * @var \Hostinger\Model\V1FolderMessagesMessage[] $data
     */
    private array $data;

    /**
     * @var \Hostinger\Model\Pagination $pagination
     */
    private \Hostinger\Model\Pagination $pagination;

    /**
    * @return \Hostinger\Model\V1FolderMessagesMessage[]
    */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesMessage[] $data data
     */
    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }
    /**
    * @return \Hostinger\Model\Pagination
    */
    public function getPagination(): \Hostinger\Model\Pagination
    {
        return $this->pagination;
    }

    /**
     * @param \Hostinger\Model\Pagination $pagination pagination
     */
    public function setPagination(\Hostinger\Model\Pagination $pagination): self
    {
        $this->pagination = $pagination;

        return $this;
    }
}

