<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1FolderMessagesUpdateFlagsResult 
{

    /**
     * @var \Hostinger\Model\V1FolderMessagesUpdateFlagsResultData $data
     */
    private \Hostinger\Model\V1FolderMessagesUpdateFlagsResultData $data;

    /**
    * @return \Hostinger\Model\V1FolderMessagesUpdateFlagsResultData
    */
    public function getData(): \Hostinger\Model\V1FolderMessagesUpdateFlagsResultData
    {
        return $this->data;
    }

    /**
     * @param \Hostinger\Model\V1FolderMessagesUpdateFlagsResultData $data data
     */
    public function setData(\Hostinger\Model\V1FolderMessagesUpdateFlagsResultData $data): self
    {
        $this->data = $data;

        return $this;
    }
}

