<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1MeResourceData 
{

    /**
     * @var string $orderResourceId
     */
    private string $orderResourceId;

    /**
     * @var \Hostinger\Model\V1MeMailbox[] $mailboxes
     */
    private array $mailboxes;

    /**
    * @return string
    */
    public function getOrderResourceId(): string
    {
        return $this->orderResourceId;
    }

    /**
     * @param string $orderResourceId Identifier of the order this API token is scoped to.
     */
    public function setOrderResourceId(string $orderResourceId): self
    {
        $this->orderResourceId = $orderResourceId;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1MeMailbox[]
    */
    public function getMailboxes(): array
    {
        return $this->mailboxes;
    }

    /**
     * @param \Hostinger\Model\V1MeMailbox[] $mailboxes Mailboxes that the authenticated API token can manage.
     */
    public function setMailboxes(array $mailboxes): self
    {
        $this->mailboxes = $mailboxes;

        return $this;
    }
}

