<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1MeMailbox 
{

    /**
     * @var string $resourceId
     */
    private string $resourceId;

    /**
     * @var string $address
     */
    private string $address;

    /**
    * @return string
    */
    public function getResourceId(): string
    {
        return $this->resourceId;
    }

    /**
     * @param string $resourceId Unique identifier of the mailbox.
     */
    public function setResourceId(string $resourceId): self
    {
        $this->resourceId = $resourceId;

        return $this;
    }
    /**
    * @return string
    */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * @param string $address Email address of the mailbox.
     */
    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }
}

