<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1QuotaQuotaResource 
{

    /**
     * @var string $resourceName
     */
    private string $resourceName;

    /**
     * @var int $usage
     */
    private int $usage;

    /**
     * @var int $limit
     */
    private int $limit;

    /**
     * @var int $percentage
     */
    private int $percentage;

    /**
    * @return string
    */
    public function getResourceName(): string
    {
        return $this->resourceName;
    }

    /**
     * @param string $resourceName Name of the quota resource as reported by the IMAP server.
     */
    public function setResourceName(string $resourceName): self
    {
        $this->resourceName = $resourceName;

        return $this;
    }
    /**
    * @return int
    */
    public function getUsage(): int
    {
        return $this->usage;
    }

    /**
     * @param int $usage Current usage of the resource (bytes for STORAGE, count for MESSAGE).
     */
    public function setUsage(int $usage): self
    {
        $this->usage = $usage;

        return $this;
    }
    /**
    * @return int
    */
    public function getLimit(): int
    {
        return $this->limit;
    }

    /**
     * @param int $limit Maximum allowed value for the resource (bytes for STORAGE, count for MESSAGE).
     */
    public function setLimit(int $limit): self
    {
        $this->limit = $limit;

        return $this;
    }
    /**
    * @return int
    */
    public function getPercentage(): int
    {
        return $this->percentage;
    }

    /**
     * @param int $percentage Usage as a percentage of the limit.
     */
    public function setPercentage(int $percentage): self
    {
        $this->percentage = $percentage;

        return $this;
    }
}

