<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1QuotaQuota 
{

    /**
     * @var \Hostinger\Model\V1QuotaQuotaResource[] $quotas
     */
    private array $quotas;

    /**
     * @var int $totalUsage
     */
    private int $totalUsage;

    /**
     * @var int $totalLimit
     */
    private int $totalLimit;

    /**
     * @var int $totalPercentage
     */
    private int $totalPercentage;

    /**
     * @var bool $supported
     */
    private bool $supported;

    /**
    * @return \Hostinger\Model\V1QuotaQuotaResource[]
    */
    public function getQuotas(): array
    {
        return $this->quotas;
    }

    /**
     * @param \Hostinger\Model\V1QuotaQuotaResource[] $quotas Per-resource quota breakdown reported by the IMAP server.
     */
    public function setQuotas(array $quotas): self
    {
        $this->quotas = $quotas;

        return $this;
    }
    /**
    * @return int
    */
    public function getTotalUsage(): int
    {
        return $this->totalUsage;
    }

    /**
     * @param int $totalUsage Aggregate storage usage across all resources, in bytes.
     */
    public function setTotalUsage(int $totalUsage): self
    {
        $this->totalUsage = $totalUsage;

        return $this;
    }
    /**
    * @return int
    */
    public function getTotalLimit(): int
    {
        return $this->totalLimit;
    }

    /**
     * @param int $totalLimit Aggregate storage limit across all resources, in bytes.
     */
    public function setTotalLimit(int $totalLimit): self
    {
        $this->totalLimit = $totalLimit;

        return $this;
    }
    /**
    * @return int
    */
    public function getTotalPercentage(): int
    {
        return $this->totalPercentage;
    }

    /**
     * @param int $totalPercentage Aggregate storage usage as a percentage of the total limit.
     */
    public function setTotalPercentage(int $totalPercentage): self
    {
        $this->totalPercentage = $totalPercentage;

        return $this;
    }
    /**
    * @return bool
    */
    public function getSupported(): bool
    {
        return $this->supported;
    }

    /**
     * @param bool $supported Whether the IMAP server reports quota information for this mailbox.
     */
    public function setSupported(bool $supported): self
    {
        $this->supported = $supported;

        return $this;
    }
}

