<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1SendRequest 
{

    /**
     * @var string[]|null $to
     */
    private ?array $to;

    /**
     * @var string|null $displayName
     */
    private ?string $displayName;

    /**
     * @var string[]|null $cc
     */
    private ?array $cc;

    /**
     * @var string[]|null $bcc
     */
    private ?array $bcc;

    /**
     * @var string|null $subject
     */
    private ?string $subject;

    /**
     * @var string|null $text
     */
    private ?string $text;

    /**
     * @var string|null $html
     */
    private ?string $html;

    /**
     * @var \Hostinger\Model\V1SendAttachment[]|null $attachments
     */
    private ?array $attachments;

    /**
     * @var \Hostinger\Model\V1SendMessageRef|null $inReplyTo
     */
    private ?\Hostinger\Model\V1SendMessageRef $inReplyTo;

    /**
     * @var \Hostinger\Model\V1SendMessageRef|null $forwardOf
     */
    private ?\Hostinger\Model\V1SendMessageRef $forwardOf;

    /**
    * @return string[]|null
    */
    public function getTo(): ?array
    {
        return $this->to;
    }

    /**
     * @param string[]|null $to to
     */
    public function setTo(?array $to): self
    {
        $this->to = $to;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * @param string|null $displayName displayName
     */
    public function setDisplayName(?string $displayName): self
    {
        $this->displayName = $displayName;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getCc(): ?array
    {
        return $this->cc;
    }

    /**
     * @param string[]|null $cc cc
     */
    public function setCc(?array $cc): self
    {
        $this->cc = $cc;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getBcc(): ?array
    {
        return $this->bcc;
    }

    /**
     * @param string[]|null $bcc bcc
     */
    public function setBcc(?array $bcc): self
    {
        $this->bcc = $bcc;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSubject(): ?string
    {
        return $this->subject;
    }

    /**
     * @param string|null $subject subject
     */
    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * @param string|null $text text
     */
    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getHtml(): ?string
    {
        return $this->html;
    }

    /**
     * @param string|null $html html
     */
    public function setHtml(?string $html): self
    {
        $this->html = $html;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1SendAttachment[]|null
    */
    public function getAttachments(): ?array
    {
        return $this->attachments;
    }

    /**
     * @param \Hostinger\Model\V1SendAttachment[]|null $attachments attachments
     */
    public function setAttachments(?array $attachments): self
    {
        $this->attachments = $attachments;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1SendMessageRef|null
    */
    public function getInReplyTo(): ?\Hostinger\Model\V1SendMessageRef
    {
        return $this->inReplyTo;
    }

    /**
     * @param \Hostinger\Model\V1SendMessageRef|null $inReplyTo Source message this is a reply to. Copies its Message-Id/References into In-Reply-To/References and flags it \\Answered. Mutually exclusive with forwardOf.
     */
    public function setInReplyTo(?\Hostinger\Model\V1SendMessageRef $inReplyTo): self
    {
        $this->inReplyTo = $inReplyTo;

        return $this;
    }
    /**
    * @return \Hostinger\Model\V1SendMessageRef|null
    */
    public function getForwardOf(): ?\Hostinger\Model\V1SendMessageRef
    {
        return $this->forwardOf;
    }

    /**
     * @param \Hostinger\Model\V1SendMessageRef|null $forwardOf Source message this forwards. Copies its Message-Id/References into In-Reply-To/References and flags it $forwarded. Mutually exclusive with inReplyTo.
     */
    public function setForwardOf(?\Hostinger\Model\V1SendMessageRef $forwardOf): self
    {
        $this->forwardOf = $forwardOf;

        return $this;
    }
}

