<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1SendAttachment 
{

    /**
     * @var string $filename
     */
    private string $filename;

    /**
     * @var string $content
     */
    private string $content;

    /**
     * @var string|null $contentType
     */
    private ?string $contentType;

    /**
     * @var string|null $cid
     */
    private ?string $cid;

    /**
     * @var string|null $encoding
     */
    private ?string $encoding;

    /**
    * @return string
    */
    public function getFilename(): string
    {
        return $this->filename;
    }

    /**
     * @param string $filename filename
     */
    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }
    /**
    * @return string
    */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param string $content Attachment body. Base64-encoded by default; set encoding to switch.
     */
    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getContentType(): ?string
    {
        return $this->contentType;
    }

    /**
     * @param string|null $contentType contentType
     */
    public function setContentType(?string $contentType): self
    {
        $this->contentType = $contentType;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getCid(): ?string
    {
        return $this->cid;
    }

    /**
     * @param string|null $cid Content-ID for inline images. Reference from HTML as <img src=\"cid:logo\">.
     */
    public function setCid(?string $cid): self
    {
        $this->cid = $cid;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getEncoding(): ?string
    {
        return $this->encoding;
    }

    /**
     * @param string|null $encoding Encoding of content. Defaults to base64.
     */
    public function setEncoding(?string $encoding): self
    {
        $this->encoding = $encoding;

        return $this;
    }
}

