<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1SendMessageRef 
{

    /**
     * @var int $uid
     */
    private int $uid;

    /**
     * @var string $folder
     */
    private string $folder;

    /**
    * @return int
    */
    public function getUid(): int
    {
        return $this->uid;
    }

    /**
     * @param int $uid UID of the source message.
     */
    public function setUid(int $uid): self
    {
        $this->uid = $uid;

        return $this;
    }
    /**
    * @return string
    */
    public function getFolder(): string
    {
        return $this->folder;
    }

    /**
     * @param string $folder Folder containing the source message.
     */
    public function setFolder(string $folder): self
    {
        $this->folder = $folder;

        return $this;
    }
}

