<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1WebhooksWebhookWithSecret 
{
    /**
     * @var string
     */
    public const EVENTS_MESSAGE_RECEIVED = 'message.received';

    /**
     * @var string
     */
    public const STATUS_ACTIVE = 'active';
    /**
     * @var string
     */
    public const STATUS_PAUSED = 'paused';
    /**
     * @var string
     */
    public const STATUS_DISABLED = 'disabled';

    /**
     * @var string $id
     */
    private string $id;

    /**
     * @var string $accountResourceId
     */
    private string $accountResourceId;

    /**
     * @var string $mailbox
     */
    private string $mailbox;

    /**
     * @var string $name
     */
    private string $name;

    /**
     * @var string $description
     */
    private ?string $description = null;

    /**
     * @var string[] $events
     */
    private array $events;

    /**
     * @var string $status
     */
    private string $status;

    /**
     * @var string $url
     */
    private string $url;

    /**
     * @var \DateTime $createdAt
     */
    private \DateTime $createdAt;

    /**
     * @var \DateTime $updatedAt
     */
    private \DateTime $updatedAt;

    /**
     * @var string $secret
     */
    private string $secret;

    /**
    * @return string
    */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @param string $id Unique webhook identifier (UUID v7).
     */
    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return string
    */
    public function getAccountResourceId(): string
    {
        return $this->accountResourceId;
    }

    /**
     * @param string $accountResourceId Resource ID of the mailbox this webhook is attached to.
     */
    public function setAccountResourceId(string $accountResourceId): self
    {
        $this->accountResourceId = $accountResourceId;

        return $this;
    }
    /**
    * @return string
    */
    public function getMailbox(): string
    {
        return $this->mailbox;
    }

    /**
     * @param string $mailbox Email address of the mailbox.
     */
    public function setMailbox(string $mailbox): self
    {
        $this->mailbox = $mailbox;

        return $this;
    }
    /**
    * @return string
    */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name name
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string
    */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description description
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
    /**
    * @return string[]
    */
    public function getEvents(): array
    {
        return $this->events;
    }

    /**
     * @param string[] $events events
     */
    public function setEvents(array $events): self
    {
        $this->events = $events;

        return $this;
    }
    /**
    * @return string
    */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status status
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
    * @return string
    */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url url
     */
    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
    /**
    * @return string
    */
    public function getSecret(): string
    {
        return $this->secret;
    }

    /**
     * @param string $secret secret
     */
    public function setSecret(string $secret): self
    {
        $this->secret = $secret;

        return $this;
    }
}

