<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1WebhooksCreateRequest 
{
    /**
     * @var string
     */
    public const EVENTS_MESSAGE_RECEIVED = 'message.received';

    /**
     * @var string
     */
    public const STATUS_ACTIVE = 'active';
    /**
     * @var string
     */
    public const STATUS_PAUSED = 'paused';
    /**
     * @var string
     */
    public const STATUS_DISABLED = 'disabled';

    /**
     * @var string $name
     */
    private string $name;

    /**
     * @var string|null $description
     */
    private ?string $description = null;

    /**
     * @var string[] $events
     */
    private array $events;

    /**
     * @var string|null $status
     */
    private ?string $status;

    /**
     * @var string $url
     */
    private string $url;

    /**
    * @return string
    */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name name
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description description
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
    /**
    * @return string[]
    */
    public function getEvents(): array
    {
        return $this->events;
    }

    /**
     * @param string[] $events events
     */
    public function setEvents(array $events): self
    {
        $this->events = $events;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string|null $status status
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
    * @return string
    */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url url
     */
    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

