<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.1.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class V1WebhooksTestResultData 
{

    /**
     * @var int $httpStatus
     */
    private int $httpStatus;

    /**
     * @var bool|null $success
     */
    private ?bool $success;

    /**
     * @var string|null $error
     */
    private ?string $error = null;

    /**
    * @return int
    */
    public function getHttpStatus(): int
    {
        return $this->httpStatus;
    }

    /**
     * @param int $httpStatus httpStatus
     */
    public function setHttpStatus(int $httpStatus): self
    {
        $this->httpStatus = $httpStatus;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getSuccess(): ?bool
    {
        return $this->success;
    }

    /**
     * @param bool|null $success success
     */
    public function setSuccess(?bool $success): self
    {
        $this->success = $success;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * @param string|null $error error
     */
    public function setError(?string $error): self
    {
        $this->error = $error;

        return $this;
    }
}

