<?php
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use Symfony\Component\Serializer\Serializer;
use Hostinger\ApiException;
use Hostinger\Configuration;
use Hostinger\ObjectSerializer;

class MessagesApi
{
    protected ClientInterface $client;

    protected Configuration $config;

    protected Serializer $serializer;

    public function __construct(
        ?Configuration $config = null,
        ?ClientInterface $client = null,
    ) {
        $this->serializer = ObjectSerializer::getSerializer();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->client = $client ?: new Client([
            'base_uri' => $this->config->getHost(),
        ]);
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function deleteAllMessages(string $mailboxResourceId, string $folder)
    {
        $request = new Request(
            method: 'DELETE',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function deleteMessage(string $mailboxResourceId, string $folder, int $uid)
    {
        $request = new Request(
            method: 'DELETE',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function deleteMessages(string $mailboxResourceId, string $folder, \Hostinger\Model\V1FolderMessagesDeleteBulkRequest $v1FolderMessagesDeleteBulkRequest)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/delete', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesDeleteBulkRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getMessage(string $mailboxResourceId, string $folder, int $uid)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesResource', JsonEncoder::FORMAT);
    }

    /**
     * @return \SplFileObject
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getMessageAttachment(string $mailboxResourceId, string $folder, int $uid, string $attachmentId)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}/attachments/{attachmentId}', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid, 'attachmentId' => $attachmentId
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\SplFileObject', JsonEncoder::FORMAT);
    }

    /**
     * @return \SplFileObject
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getMessageSource(string $mailboxResourceId, string $folder, int $uid)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}/source', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\SplFileObject', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesMessageTextResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getMessageText(string $mailboxResourceId, string $folder, int $uid)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}/text', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesMessageTextResource', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesCollection
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function listMessages(string $mailboxResourceId, string $folder, ?int $page = 1, ?int $perPage = 25, ?string $sort = '-uid')
    {
        $query = http_build_query(
            array_filter(
                $this->serializer->normalize([
                        'page' => $page,
                        'perPage' => $perPage,
                        'sort' => $sort,
                ])
            )
        );

        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]) . '?' . $query,
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesCollection', JsonEncoder::FORMAT);
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function moveMessage(string $mailboxResourceId, string $folder, int $uid, \Hostinger\Model\V1FolderMessagesMoveRequest $v1FolderMessagesMoveRequest)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}/move', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesMoveRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function moveMessages(string $mailboxResourceId, string $folder, \Hostinger\Model\V1FolderMessagesMoveBulkRequest $v1FolderMessagesMoveBulkRequest)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/move', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesMoveBulkRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function patchMessage(string $mailboxResourceId, string $folder, int $uid, \Hostinger\Model\V1FolderMessagesFlagsRequest $v1FolderMessagesFlagsRequest)
    {
        $request = new Request(
            method: 'PATCH',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/{uid}', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder, 'uid' => $uid
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesFlagsRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesResource', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesCollection
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function searchMessages(string $mailboxResourceId, string $folder, ?int $page = 1, ?int $perPage = 25, ?string $sort = '-uid', ?\Hostinger\Model\V1FolderMessagesSearchRequest $v1FolderMessagesSearchRequest = null)
    {
        $query = http_build_query(
            array_filter(
                $this->serializer->normalize([
                        'page' => $page,
                        'perPage' => $perPage,
                        'sort' => $sort,
                ])
            )
        );

        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/search', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]) . '?' . $query,
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesSearchRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesCollection', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1FolderMessagesUpdateFlagsResult
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function updateMessageFlags(string $mailboxResourceId, string $folder, \Hostinger\Model\V1FolderMessagesFlagsBulkRequest $v1FolderMessagesFlagsBulkRequest)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/folders/{folder}/messages/flags', [
                'mailboxResourceId' => $mailboxResourceId, 'folder' => $folder
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1FolderMessagesFlagsBulkRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1FolderMessagesUpdateFlagsResult', JsonEncoder::FORMAT);
    }

    /**
     * @param array<string, mixed> $values
     */
    private function buildResourcePath(string $path, array $values): string
    {
        foreach ($values as $key => $value) {
            if (is_array($value)) {
                $value = implode(',', $value);
            }

            $path = str_replace('{' . $key . '}', $value, $path);
        }

        return $path;
    }

    /**
     * @return array<string, string>
     */
    private function getHeaders(): array
    {
        return [
            'Authorization' => 'Bearer ' . $this->config->getAccessToken(),
            'Content-Type' => 'application/json',
            'User-Agent' => $this->config->getUserAgent(),
        ];
    }

    /**
     * @return array<string, string>
     */
    private function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
