<?php
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/**
 * Hostinger Email API PHP SDK
 *
 * API Version: 1.0.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use Symfony\Component\Serializer\Serializer;
use Hostinger\ApiException;
use Hostinger\Configuration;
use Hostinger\ObjectSerializer;

class WebhooksApi
{
    protected ClientInterface $client;

    protected Configuration $config;

    protected Serializer $serializer;

    public function __construct(
        ?Configuration $config = null,
        ?ClientInterface $client = null,
    ) {
        $this->serializer = ObjectSerializer::getSerializer();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->client = $client ?: new Client([
            'base_uri' => $this->config->getHost(),
        ]);
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * @return \Hostinger\Model\V1WebhooksResourceWithSecret
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function createWebhook(string $mailboxResourceId, \Hostinger\Model\V1WebhooksCreateRequest $v1WebhooksCreateRequest)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks', [
                'mailboxResourceId' => $mailboxResourceId
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1WebhooksCreateRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksResourceWithSecret', JsonEncoder::FORMAT);
    }

    /**
     * @return void
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function deleteWebhook(string $mailboxResourceId, string $webhook)
    {
        $request = new Request(
            method: 'DELETE',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks/{webhook}', [
                'mailboxResourceId' => $mailboxResourceId, 'webhook' => $webhook
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }
    }

    /**
     * @return \Hostinger\Model\V1WebhooksResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getWebhook(string $mailboxResourceId, string $webhook)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks/{webhook}', [
                'mailboxResourceId' => $mailboxResourceId, 'webhook' => $webhook
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksResource', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1WebhooksCollection
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function listWebhooks(string $mailboxResourceId, ?string $status = null, ?int $page = 1, ?int $perPage = 15)
    {
        $query = http_build_query(
            array_filter(
                $this->serializer->normalize([
                        'status' => $status,
                        'page' => $page,
                        'perPage' => $perPage,
                ])
            )
        );

        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks', [
                'mailboxResourceId' => $mailboxResourceId
            ]) . '?' . $query,
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksCollection', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1WebhooksResourceWithSecret
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function regenerateWebhookSecret(string $mailboxResourceId, string $webhook)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks/{webhook}/regenerate-secret', [
                'mailboxResourceId' => $mailboxResourceId, 'webhook' => $webhook
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksResourceWithSecret', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1WebhooksTestResult
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function testWebhook(string $mailboxResourceId, string $webhook)
    {
        $request = new Request(
            method: 'POST',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks/{webhook}/test', [
                'mailboxResourceId' => $mailboxResourceId, 'webhook' => $webhook
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksTestResult', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\V1WebhooksResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function updateWebhook(string $mailboxResourceId, string $webhook, \Hostinger\Model\V1WebhooksUpdateRequest $v1WebhooksUpdateRequest)
    {
        $request = new Request(
            method: 'PATCH',
            uri: $this->buildResourcePath('/api/v1/mailboxes/{mailboxResourceId}/webhooks/{webhook}', [
                'mailboxResourceId' => $mailboxResourceId, 'webhook' => $webhook
            ]),
            headers: $this->getHeaders(),
            body: $this->serializer->serialize($v1WebhooksUpdateRequest, JsonEncoder::FORMAT),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\V1WebhooksResource', JsonEncoder::FORMAT);
    }

    /**
     * @param array<string, mixed> $values
     */
    private function buildResourcePath(string $path, array $values): string
    {
        foreach ($values as $key => $value) {
            if (is_array($value)) {
                $value = implode(',', $value);
            }

            $path = str_replace('{' . $key . '}', $value, $path);
        }

        return $path;
    }

    /**
     * @return array<string, string>
     */
    private function getHeaders(): array
    {
        return [
            'Authorization' => 'Bearer ' . $this->config->getAccessToken(),
            'Content-Type' => 'application/json',
            'User-Agent' => $this->config->getUserAgent(),
        ];
    }

    /**
     * @return array<string, string>
     */
    private function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
