<?php

/**
 * Hostinger Mail API PHP SDK
 *
 * API Version: 1.0.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Model;

use PHPUnit\Framework\TestCase;

class V1FolderMessagesSearchRequestTest extends TestCase
{

    public static function setUpBeforeClass(): void
    {
    }

    public function setUp(): void
    {
    }

    public function tearDown(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function testV1FolderMessagesSearchRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySince()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyBefore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyFlags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyFrom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyTo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyCc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyBody()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyHeader()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyLarger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySmaller()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
